### ISSUE TITLE
[BUG]H2R Graphics timer can't show

### ISSUE THREAD

**Issue by tychoua** [bitfocus/companion-module-h2r-graphics#2]
**Describe the bug**

When I want to use companion to make g2h graphics timer show, but it fails.
Whether in a local area network or the same computer environment.

**Expected behavior**
During execution, the execution result will appear in the fill window. (display time)
But no success

**Screenshots**
![Image20200414153836](https://user-images.githubusercontent.com/63579380/79198450-13ab9f80-7e66-11ea-83dc-c16d6f77647f.png)
![Image20200414153848](https://user-images.githubusercontent.com/63579380/79198466-18705380-7e66-11ea-98f2-9871f5f96f25.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser ：firefox
 - Companion Version： 2.0.0 beta

**Comment by iamjohnbarker** [comment]
Unfortunately, this is a bug with H2R Graphics, rather than the implementation within Companion. Fixing in a future update.

**Comment by josephdadams** [comment]
Then I'll close this.

**Comment by iamjohnbarker** [comment]
@tychoua  - Fixed in the latest version of H2R Graphics (0.0.8) which was just released! https://heretorecord.com/graphics#download

**Comment by tychoua** [comment]
> @tychoua - Fixed in the latest version of H2R Graphics (0.0.8) which was just released! https://heretorecord.com/graphics#download

@iamjohnbarker 
After testing, the new version (0.0.8) still cannot be executed successfully

**Comment by iamjohnbarker** [comment]
My mistake - The thing I fixed was the 'Generic OSC' integration which was broken before also. Will take another look at this as soon as I can

**Comment by iamjohnbarker** [comment]
Okay - me again - just tested with 2.0.0 of Companion and 0.0.8 of H2R Graphics and things are working just fine on my end to show/hide the timer.

The only thing to consider is that there does need to be a 'time' entered in H2R Graphics for some of the timer options, so an unsuccessful submit will return an error in H2R Graphics which will clearly state 'This field needs to be filled in' within the Timer section of the interface.

Note also that H2R Graphics only listens on 127.0.0.1 right now and the port should match whatever port you have configured in the H2R Graphics settings tab.

**Comment by tychoua** [comment]
I tried the operation and it still didn't work. Maybe I misunderstood what you want to express. Can you please give me some guidance?
![1589446602082](https://user-images.githubusercontent.com/63579380/81915232-e6891300-9604-11ea-9e8f-b8039d321dcb.jpg)
![1589446524875](https://user-images.githubusercontent.com/63579380/81915240-e8eb6d00-9604-11ea-9789-ba1905b6217b.jpg)
![1589446707034](https://user-images.githubusercontent.com/63579380/81915253-eb4dc700-9604-11ea-8e75-c06b8f027b17.jpg)
![1589446686672](https://user-images.githubusercontent.com/63579380/81915268-f0ab1180-9604-11ea-9cf8-18d23406e5ca.jpg)

**Comment by haakonnessjoen** [comment]
You are putting multiple things on the same port.

Let companion GUI Interface stay on another port, like 8000 or 3000 or something similar. (The window that says Running). Make sure you restart h2r and companion after that change.

**Comment by tychoua** [comment]
I changed the companion GUI Interface port to 8000, then restarted h2r and companion, but it still didn't run smoothly. Is there anything else I might have missed?

**Comment by iamjohnbarker** [comment]
Did you ever get this working @tychoua? I sure hope so!
